In [1]:
from alphalab.performance.metrics import *
from alphalab.performance.summary import performance_summary

In [5]:
df_bench_price = pd.read_excel("data/全收益指数价格.xlsx", index_col=0, skiprows=1)
df_bench_ret = df_bench_price.pct_change().dropna()
df_bench_ret = df_bench_ret.loc[pd.to_datetime("2015-01-01"):pd.to_datetime("2026-04-30")]
df_bench_ret

,300收益,500收益,800收益,50收益,A100收益,中证A500全收益,300质量全收益,300收价,300收成,300红利低波全收益,中证1000全收益,中证A50全收益,深证100R,500等权全收益
2015-01-05,0.030516,0.017717,0.027343,0.026369,0.032351,0.029738,0.036166,0.035587,0.028757,0.035679,0.003694,0.036359,0.036801,0.019945
2015-01-06,-0.000132,0.011610,0.002752,-0.007637,-0.004834,0.006966,0.015145,-0.008793,-0.002142,-0.002949,0.020266,-0.001095,0.012206,0.010144
2015-01-07,0.000750,0.001529,0.000942,0.002217,0.000997,-0.000847,-0.004210,-0.002466,-0.008147,0.002429,-0.000911,0.001670,-0.003561,0.000858
2015-01-08,-0.023199,-0.008054,-0.019455,-0.029267,-0.028026,-0.018381,-0.017651,-0.030238,-0.023001,-0.035645,-0.000431,-0.019363,-0.011297,-0.008206
2015-01-09,-0.003300,-0.006425,-0.004082,0.004755,0.000951,-0.003325,-0.007318,0.002718,-0.001379,-0.003803,-0.005856,-0.007542,-0.010516,-0.007701
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-24,-0.003513,-0.005706,-0.004139,0.005844,0.002392,-0.003481,0.002376,-0.003710,-0.003987,-0.000692,-0.006993,-0.000344,-0.009111,-0.007832
2026-04-27,0.000331,0.006219,0.002011,-0.002034,-0.000400,0.002172,-0.006927,-0.003933,-0.001683,-0.004658,0.004188,-0.003819,0.001876,0.003926
2026-04-28,-0.002629,-0.011415,-0.005147,0.003868,-0.003864,-0.005962,0.001499,0.006364,-0.007217,0.011133,-0.013401,-0.005429,-0.009694,-0.008929
2026-04-29,0.011011,0.016929,0.012696,0.005790,0.014514,0.014160,0.011858,0.006823,0.015031,0.001916,0.014169,0.016790,0.018692,0.014629
2026-04-30,-0.000536,0.000958,-0.000109,0.006066,0.002452,0.001284,-0.008076,-0.005751,0.000905,-0.002600,0.004727,-0.003729,-0.002322,-0.000753

In [7]:
performance_summary(df_bench_ret)

,开始日期,结束日期,区间收益,年化收益率,年化波动率,夏普比率,最大回撤,卡玛比率,胜率,盈亏比
300收益,2015-01-05,2026-04-30,0.747411,0.052029,0.214294,0.242795,-0.460589,0.112963,0.519811,0.985447
500收益,2015-01-05,2026-04-30,0.8095,0.055373,0.252616,0.219197,-0.641433,0.086327,0.53108,0.940695
800收益,2015-01-05,2026-04-30,0.760763,0.052757,0.2179,0.242118,-0.485263,0.108719,0.51763,0.994387
50收益,2015-01-05,2026-04-30,0.58781,0.042912,0.211167,0.203215,-0.43796,0.097982,0.51036,1.01621
A100收益,2015-01-05,2026-04-30,0.814502,0.055638,0.214543,0.259331,-0.465473,0.119529,0.513631,1.012366
中证A500全收益,2015-01-05,2026-04-30,0.999582,0.064996,0.217922,0.298256,-0.47904,0.135681,0.517993,1.001922
300质量全收益,2015-01-05,2026-04-30,1.509733,0.087218,0.199063,0.438143,-0.402162,0.216872,0.522356,1.005724
300收价,2015-01-05,2026-04-30,1.041911,0.067026,0.203089,0.330031,-0.396936,0.168858,0.515085,1.018902
300收成,2015-01-05,2026-04-30,0.89359,0.059738,0.237396,0.25164,-0.609159,0.098067,0.519447,0.987675
300红利低波全收益,2015-01-05,2026-04-30,1.433254,0.084165,0.183127,0.459595,-0.345358,0.243702,0.51872,1.028202
中证1000全收益,2015-01-05,2026-04-30,0.534901,0.039705,0.274402,0.144697,-0.717889,0.055308,0.543075,0.885612
中证A50全收益,2015-01-05,2026-04-30,1.390431,0.082417,0.217819,0.378372,-0.428528,0.192325,0.512177,1.038279
深证100R,2015-01-05,2026-04-30,1.15479,0.072256,0.250649,0.288276,-0.524712,0.137706,0.507452,1.043734
500等权全收益,2015-01-05,2026-04-30,0.868386,0.058449,0.250699,0.233143,-0.637254,0.09172,0.534715,0.930013